// ignore_for_file: constant_identifier_names

enum CHART_TYPES {
  PREVIOUS_CURRENT_COMPARISON_BAR,
  TAG_PIE,
  TAG_BAR,
  SPENT_VS_DEPOSITED_PIE,
  SPENT_VS_INCOME_PIE,
  DEPOSIT_DISTRIBUTION_DOUBLE_BAR,
}
